language: scala

scala:
  - 2.11.1

branches:
  only:
    - master

env:

before_install:
  - sudo apt-get update -qq

install:

script:
  - "cd $TRAVIS_BUILD_DIR"
  - "sbt ++$TRAVIS_SCALA_VERSION compile"
  - "sbt ++$TRAVIS_SCALA_VERSION scalastyle"
  - "sbt ++$TRAVIS_SCALA_VERSION test"
  - "sbt ++$TRAVIS_SCALA_VERSION publish-local"

jdk:
  - oraclejdk7
  - oraclejdk8

notifications:
  email: false
