language: scala

scala:
  - 2.11.1

branches:
  only:
    - master

env:
  - ACTIVATORVER=1.2.12
  - ACTIVATOR_VERSION=1.2.12 \
    ACTIVATOR_ZIP_FILE=typesafe-activator-${ACTIVATOR_VERSION}-minimal.zip \
    ACTIVATOR_ZIP_URL=http://downloads.typesafe.com/typesafe-activator/${ACTIVATOR_VERSION}/${ACTIVATOR_ZIP_FILE} \
    ACTIVATOR_BIN=${TRAVIS_BUILD_DIR}/activator-${ACTIVATOR_VERSION}-minimal/activator

before_install:
  - sudo apt-get update -qq

install:
  - wget -v ${ACTIVATOR_ZIP_URL}
  - unzip -oq ${ACTIVATOR_ZIP_FILE}

script:
  - "cd $TRAVIS_BUILD_DIR"
  - "sbt ++$TRAVIS_SCALA_VERSION compile"
  - "sbt ++$TRAVIS_SCALA_VERSION scalastyle"
  - "sbt ++$TRAVIS_SCALA_VERSION test"
  - "sbt ++$TRAVIS_SCALA_VERSION publish-local"

jdk:
  - oraclejdk7
  - oraclejdk8

notifications:
  email: false
