language: scala

branches:
  only:
    - master

env:
  - "ACTIVATORVER=1.2.12"

scala:
  - 2.11.1

before_install:
  - sudo apt-get update -qq

before_script: 
  - wget -v http://downloads.typesafe.com/typesafe-activator/${ACTIVATORVER}/typesafe-activator-${ACTIVATORVER}-minimal.zip
  - unzip -q typesafe-activator-${ACTIVATORVER}-minimal.zip
  - cp -rf activator-${ACTIVATORVER}-minimal/*.* . && rm -rf activator-${ACTIVATORVER}-minimal

script:
  - ./activator compile

jdk:
  - oraclejdk7
  - oraclejdk8

notifications:
  email:
    - edwardt.tril@gmail.com
